### ISSUE TITLE
OrderByDescending.ThenByDescending.ThenByDescending not working correct

### ISSUE THREAD

**Issue by wuhuizuo** [ahmetb/go-linq#81] opened 2019-06-11 11:12 UTC
```go
package xxx

import (
	"reflect"
	"testing"
	"strings"
	"fmt"
	linq "github.com/ahmetb/go-linq"
)

type Row map[string]interface{}

func maxMatricData(data []Row, groupKeys []string, metricKeys []string) []Row {
	if len(metricKeys) == 0 {
		return data
	}

	var maxData []Row
	q := linq.
		From(data).
		GroupBy(
			func(d interface{}) interface{} {
				r := d.(Row)
				var vals []string
				for _, k := range groupKeys {
					vals = append(vals, fmt.Sprintf("%v", r[k]))
				}
				return strings.Join(vals, ",")
			},
			func(d interface{}) interface{} { return d },
		).
		Select(func(g interface{}) interface{} {
			query := linq.From(g.(linq.Group).Group).
				OrderByDescending(func(r interface{}) interface{} { return r.(Row)[metricKeys[0]] })
			if len(metricKeys) > 1 {
				for _, k := range metricKeys[1:] {
					query = query.ThenByDescending(func(r interface{}) interface{} { return r.(Row)[k] })
				}
			}
			return query.First()
		}).
		OrderByDescending(func(r interface{}) interface{} {
			return r.(Row)[groupKeys[0]]
		})

       // FIXME: bug for more than 2rd order by Descending
	for _, k := range groupKeys[1:] {
		q = q.ThenByDescending(func(r interface{}) interface{} {
			return r.(Row)[k]
		})
	}
	q.ToSlice(&maxData)

	return maxData
}

func Test_maxMatricData(t *testing.T) {
	type args struct {
		data       []Row
		groupKeys  []string
		metricKeys []string
	}
	tests := []struct {
		name string
		args args
		want []Row
	}{
		{
			"default",
			args{
				[]Row{
					Row{"a": "a1", "b": "b3", "c": "1", "v1": 17, "v2": 21, "v3": 31},
					Row{"a": "a1", "b": "b1", "c": "1", "v1": 11, "v2": 21, "v3": 31},
					Row{"a": "a1", "b": "b2", "c": "1", "v1": 15, "v2": 21, "v3": 31},
					Row{"a": "a1", "b": "b1", "c": "1", "v1": 13, "v2": 21, "v3": 31},
					Row{"a": "a1", "b": "b2", "c": "1", "v1": 14, "v2": 21, "v3": 31},
					Row{"a": "a1", "b": "b1", "c": "1", "v1": 11, "v2": 22, "v3": 31},
					Row{"a": "a1", "b": "b2", "c": "1", "v1": 15, "v2": 21, "v3": 32},
				},
				[]string{"a", "b", "c"}, // passed when: []string{"a", "b"}
				[]string{"v1"},
			},
			[]Row{
				Row{"a": "a1", "b": "b3", "c": "1", "v1": 17, "v2": 21, "v3": 31},
				Row{"a": "a1", "b": "b2", "c": "1", "v1": 15, "v2": 21, "v3": 31},
				Row{"a": "a1", "b": "b1", "c": "1", "v1": 13, "v2": 21, "v3": 31},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := maxMatricData(tt.args.data, tt.args.groupKeys, tt.args.metricKeys); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("maxMatricData() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

## testing output:
```
--- FAIL: Test_maxMatricData (0.00s)
    --- FAIL: Test_maxMatricData/default (0.00s)
        e:\Apps\goApps\git.code.oa.com\WeishiQA\QualityHttpServer\queries\druid\handler_test.go:44: maxMatricData() = [map[a:a1 b:b3 c:1 v1:17 v2:21 v3:31] map[a:a1 b:b1 c:1 v1:13 v2:21 v3:31] map[a:a1 b:b2 c:1 v1:15 v2:21 v3:31]], want [map[a:a1 b:b3 c:1 v1:17 v2:21 v3:31]  map[a:a1 b:b2 c:1 v1:15 v2:21 v3:31]  map[a:a1 b:b1 c:1 v1:13 v2:21 v3:31]]
FAIL
FAIL	WeishiQA/QualityHttpServer/queries/druid	0.277s
Error: Tests failed.
```

**Comment by wuhuizuo** [comment] 2019-06-11 11:14
same problem when OrderBy.ThenBy.ThenBy

**Comment by ahmetb** [comment] 2019-06-24 23:00
cc: @cleitonmarx wdyt?

**Comment by cleitonmarx** [comment] 2019-06-25 17:43
Sorry for the lack of communication here, it has been a busy week. I'll try to reproduce the same scenario and share my thoughts until this weekend.

**Comment by cleitonmarx** [comment] 2019-07-02 23:43
Hey @wuhuizuo, it looks like a variable scope problem in the `for` loops. This fixes in your function should make your test pass:

**Comment by cleitonmarx** [comment] 2019-07-08 20:53
I'm closing this issue since it is not a bug.

**Closed by cleitonmarx** 2019-07-08 20:53 UTC
